import csv
file1 = input('Path of original infos.csv:')
file2 = input('Path of info_new.csv generated by Phigros_Resource:')
dic1 = {}
dic2 = {}
with open(file2, 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    for row in reader:
        if row:
            dic2[row[1]] = row[2:]
            if len(dic2[row[1]]) == 8:
                dic2[row[1]].insert(3, '0')
                dic2[row[1]].insert(3, '0')
                dic2[row[1]].append('0')
                dic2[row[1]].append('0')
            if len(dic2[row[1]]) == 10:
                dic2[row[1]].insert(4, '0')
                dic2[row[1]].append('0')
with open(file1, 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    next(reader)
    for row in reader:
        if row[1]:
            if row[0] in dic2:
                dic1[row[0]] = row[1:]
            else:
                # pass
                print(f'{row[0]} not found in info_new.csv')
new = {}
for key in dic2:
    if key not in dic1:
        print(f'{key} not found in infos.csv')
        new[key] = dic2[key]
diff = {}
for key in dic1:
    if key in dic2:
        for i in range(len(dic1[key])):
            lst = ['EZ', 'HD', 'IN', 'AT', 'Legacy', 'Composer', 'Illustrator', 'CharterEZ', 'CharterHD', 'CharterIN', 'CharterAT', 'CharterLegacy']
            exclude = ['Legacy', 'CharterLegacy']
            if dic1[key][i] != dic2[key][i] and lst[i] not in exclude and dic2[key][i] != '0':
                print(f'{key} {lst[i]}: {dic1[key][i]} -> {dic2[key][i]}')
                diff[key + str(i)] = dic2[key][i]
print('write into infos_new.csv')
with open('infos_new.csv', 'w', encoding='utf-8', newline='') as f:
    with open(file1, 'r', encoding='utf-8') as f1:
        reader = csv.reader(f1)
        writer = csv.writer(f)
        for row in reader:
            x = row
            if row[1]:
                for i in range(12):
                    i = str(i)
                    if row[0] + i in diff:
                        x[1 + int(i)] = diff[row[0] + i]
            if row[0] in new:
                pass
            writer.writerow(x)
for k, v in new.items():
    print(','.join([k] + v))