import csv

def normalize_data(data):
    """Normalize data length to 12 fields."""
    if len(data) == 8:
        data.insert(3, '0')
        data.insert(3, '0')
        data.append('0')
        data.append('0')
    if len(data) == 10:
        data.insert(4, '0')
        data.append('0')
    return data

def compare_meta(file1, file2, exclude_legacy=True, exclude_zero=True):
    """
    Compare two CSV files containing song metadata.
    
    Args:
        file1: Path to original infos.csv
        file2: Path to info_new.csv (generated by Phigros_Resource)
        exclude_legacy: Whether to exclude Legacy and CharterLegacy fields from comparison
        exclude_zero: Whether to exclude zero values from comparison
    
    Returns:
        dict with 'new' (songs only in file2), 'diff' (field differences), and 'missing' (songs only in file1)
    """
    dic1 = {}
    dic2 = {}
    
    # Read file2
    with open(file2, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            if row:
                dic2[row[1]] = normalize_data(row[2:])
    
    # Read file1
    with open(file1, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            if row[1]:
                if row[0] in dic2:
                    dic1[row[0]] = row[1:]
                else:
                    print(f'{row[0]} not found in info_new.csv')
    
    # Find new songs in file2
    new = {}
    for key in dic2:
        if key not in dic1:
            print(f'{key} not found in infos.csv')
            new[key] = dic2[key]
    
    # Compare fields
    diff = {}
    lst = ['EZ', 'HD', 'IN', 'AT', 'Legacy', 'Composer', 'Illustrator', 'CharterEZ', 'CharterHD', 'CharterIN', 'CharterAT', 'CharterLegacy']
    exclude = ['Legacy', 'CharterLegacy'] if exclude_legacy else []
    
    for key in dic1:
        if key in dic2:
            for i in range(len(dic1[key])):
                should_exclude = lst[i] in exclude or (exclude_zero and dic2[key][i] == '0')
                if dic1[key][i] != dic2[key][i] and not should_exclude:
                    print(f'{key} {lst[i]}: {dic1[key][i]} -> {dic2[key][i]}')
                    diff[key + str(i)] = dic2[key][i]
    
    return {'new': new, 'diff': diff, 'missing': list(set(dic1.keys()) - set(dic2.keys()))}

def apply_diff(file1, diff, new, output='infos_new.csv'):
    """
    Apply differences to original file and write to output.
    
    Args:
        file1: Path to original infos.csv
        diff: Dict of differences from compare_meta
        new: Dict of new songs from compare_meta
        output: Path to output CSV file
    """
    with open(output, 'w', encoding='utf-8', newline='') as f:
        with open(file1, 'r', encoding='utf-8') as f1:
            reader = csv.reader(f1)
            writer = csv.writer(f)
            for row in reader:
                x = row
                if row[1]:
                    for i in range(12):
                        key = row[0] + str(i)
                        if key in diff:
                            x[1 + i] = diff[key]
                writer.writerow(x)
            writer.writerow([''] * 13)
            for k, v in new.items():
                writer.writerow([k] + v)
    print(f'Written to {output}')

def compare_meta_interactive():
    """Interactive version that prompts for file paths and writes output."""
    file1 = input('Path of original infos.csv: ')
    file2 = input('Path of info_new.csv generated by Phigros_Resource: ')
    
    result = compare_meta(file1, file2)
    
    if result['diff'] or result['new']:
        apply_diff(file1, result['diff'], result['new'])
        print('New songs:')
        for k, v in result['new'].items():
            print(','.join([k] + v))
    
    return result

if __name__ == '__main__':
    compare_meta_interactive()